apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-5nw1
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0031-tenant/tkrw-pr712-0075-0031-app/devfile-sample-5nw1@sha256:2cea09f08157c3ba9f82fbbe48102385052e6eabb7443a65025c78754fe5cd8d
        name: my-nodejs
        resources: {}
status: {}
